export const mockData = {
  institution: { name: "梅山县职业技术学校", fullName: "梅山县职业技术学校 · STEM 实训中心", type: "vocational", location: "中部某县城", departments: 3, annualBudget: 1800000, note: "县级职教中心 · 服务本地产业升级 · 学生实训即上岗" },
  user: { name: "刘建国", role: "实训中心主任", subRole: "电子技术高级讲师", avatar: "刘", yearsTeaching: 16, bio: "从教16年，带学生做过工厂自动化改造，拿过省级技能竞赛奖" },
  stats: { totalStudents: 826, studentChange: 8.3, activeTeachers: 42, teacherChange: 2.4, totalDevices: 203, deviceChange: 12.5, employmentRate: 94.5, employmentChange: 2.1, enterprisePartners: 23, partnerChange: 5, incubatingProjects: 6, projectChange: 50 },
  deviceUsage: [{ month: "9月", inUse: 178, total: 203 }, { month: "10月", inUse: 185, total: 203 }, { month: "11月", inUse: 192, total: 203 }, { month: "12月", inUse: 180, total: 203 }, { month: "1月", inUse: 196, total: 203 }, { month: "2月", inUse: 188, total: 203 }],
  deviceTypes: [{ name: "嵌入式开发板", value: 60 }, { name: "电工电子实训台", value: 45 }, { name: "传感器实验台", value: 30 }, { name: "焊接工作台", value: 25 }, { name: "小型PLC套件", value: 20 }, { name: "3D打印机", value: 6 }, { name: "其他设备", value: 17 }],
  equipment: [
    { id: 1, name: "嵌入式开发板", model: "STM32F103 / ESP32", total: 60, available: 48, inUse: 12, status: "正常", lab: "嵌入式实验室 201" },
    { id: 2, name: "电工电子实训台", model: "通用型 YL-135", total: 45, available: 38, inUse: 7, status: "正常", lab: "电工电子实训中心" },
    { id: 3, name: "传感器实验台", model: "YL-998 型", total: 30, available: 25, inUse: 5, status: "正常", lab: "传感技术实验室 203" },
    { id: 4, name: "焊接工作台", model: "恒温焊台 936型", total: 25, available: 20, inUse: 5, status: "正常", lab: "电子工艺实训室 102" },
    { id: 5, name: "小型PLC套件", model: "FX3U-24MR", total: 20, available: 16, inUse: 4, status: "正常", lab: "自动化实训室 301" },
    { id: 6, name: "3D打印机", model: "Creality Ender-3", total: 6, available: 4, inUse: 2, status: "1台待维修", lab: "创客工坊 101" },
    { id: 7, name: "示波器", model: "RIGOL DS1054Z", total: 12, available: 10, inUse: 2, status: "正常", lab: "电子测量实验室 202" },
  ],
  consumables: {
    totalItems: 48, lowStockCount: 7,
    inventory: [
      { id: 1, name: "焊锡丝", spec: "0.8mm 含松香", stock: 12, safetyStock: 20, unit: "卷", status: "紧缺" },
      { id: 2, name: "电子元器件包", spec: "电阻/电容/二极管", stock: 60, safetyStock: 50, unit: "套", status: "正常" },
      { id: 3, name: "PLA 3D打印耗材", spec: "1.75mm 各色", stock: 5, safetyStock: 12, unit: "卷", status: "紧缺" },
      { id: 4, name: "覆铜板", spec: "单面 10x15cm", stock: 150, safetyStock: 100, unit: "片", status: "正常" },
      { id: 5, name: "杜邦线套装", spec: "公母/母母", stock: 18, safetyStock: 25, unit: "套", status: "紧缺" },
      { id: 6, name: "继电器模块", spec: "5V/12V 单路", stock: 40, safetyStock: 30, unit: "个", status: "正常" },
      { id: 7, name: "步进电机驱动", spec: "A4988", stock: 8, safetyStock: 15, unit: "个", status: "紧缺" },
      { id: 8, name: "传感器模块套装", spec: "温湿度/超声波/红外", stock: 35, safetyStock: 25, unit: "套", status: "正常" },
      { id: 9, name: "面包板", spec: "830孔", stock: 12, safetyStock: 20, unit: "块", status: "紧缺" },
      { id: 10, name: "LED灯珠套装", spec: "红/绿/蓝 5mm", stock: 350, safetyStock: 200, unit: "颗", status: "正常" },
      { id: 11, name: "热缩管套装", spec: "各规格", stock: 5, safetyStock: 10, unit: "盒", status: "紧缺" },
      { id: 12, name: "接线端子", spec: "5mm间距", stock: 15, safetyStock: 20, unit: "包", status: "紧缺" },
    ],
    borrowRecords: [
      { id: 1, borrower: "李明", role: "学生", class: "电子2101", items: "焊锡丝x2、电子元器件x8", purpose: "毕业设计·温控系统", date: "2月18日", status: "使用中", avatar: "李" },
      { id: 2, borrower: "张老师", role: "教师", class: "—", items: "杜邦线x5、传感器模块x3", purpose: "电子工艺课程", date: "2月16日", status: "已归还", avatar: "张" },
      { id: 3, borrower: "王磊", role: "学生", class: "机电2101", items: "步进电机驱动x2、继电器x8", purpose: "孵化器·自动分拣样机", date: "2月15日", status: "使用中", avatar: "王" },
      { id: 4, borrower: "陈静", role: "学生", class: "电子2102", items: "覆铜板x15、传感器x3", purpose: "孵化器·水位报警器", date: "2月14日", status: "已归还", avatar: "陈" },
      { id: 5, borrower: "刘老师", role: "教师", class: "—", items: "面包板x6、LED灯珠x100", purpose: "技能竞赛集训", date: "2月12日", status: "使用中", avatar: "刘" },
    ],
    purchaseRequests: [
      { id: 1, item: "焊锡丝 0.8mm", quantity: 30, cost: 420, requester: "张老师", reason: "库存低于安全线，影响实训进度", status: "待审批" },
      { id: 2, item: "PLA耗材 各色套装", quantity: 15, cost: 900, requester: "刘主任", reason: "孵化器项目3D打印打样急需", status: "已批准" },
      { id: 3, item: "步进电机驱动 A4988", quantity: 12, cost: 360, requester: "王磊(学生)", reason: "孵化器·自动分拣样机配套", status: "待审批" },
      { id: 4, item: "面包板 830孔", quantity: 15, cost: 120, requester: "刘老师", reason: "竞赛集训日常消耗补充", status: "已批准" },
    ],
  },
  enterprises: [
    { id: 1, name: "永利电子厂", type: "电子元器件组装", projects: 3, students: 25, logo: "永", color: "from-blue-500 to-blue-700", desc: "缺自动化检测方案" },
    { id: 2, name: "华丰机械加工厂", type: "五金零件加工", projects: 2, students: 18, logo: "华", color: "from-orange-500 to-orange-700", desc: "缺数控编程人员" },
    { id: 3, name: "鑫达自动化设备", type: "小型非标设备", projects: 2, students: 15, logo: "鑫", color: "from-green-500 to-green-700", desc: "缺嵌入式开发" },
    { id: 4, name: "绿源新能源科技", type: "太阳能设备安装", projects: 1, students: 12, logo: "绿", color: "from-teal-500 to-teal-700", desc: "缺智能监控系统" },
    { id: 5, name: "瑞恒智能安防", type: "安防监控工程", projects: 1, students: 10, logo: "瑞", color: "from-purple-500 to-purple-700", desc: "缺物联网方案" },
  ],
  cooperationProjects: [
    { id: 1, name: "电子元件自动分拣装置", enterprise: "永利电子厂", progress: 65, students: 8, stage: "样机调试", painPoint: "靠人工分拣效率低，出错率高", value: "学生做嵌入式控制+传感器方案，厂方提供物料和试用场景" },
    { id: 2, name: "数控车床自动上下料改造", enterprise: "华丰机械加工厂", progress: 40, students: 6, stage: "方案设计", painPoint: "3台老式车床靠人工上下料，效率低", value: "学生设计PLC+气缸自动送料，厂方给设备练手" },
    { id: 3, name: "小型冲压件计数分装系统", enterprise: "鑫达自动化设备", progress: 75, students: 5, stage: "现场试运行", painPoint: "小批量冲压件统计靠手数", value: "学生做红外计数+传送带分装，已出样机" },
    { id: 4, name: "光伏板倾斜角度自动调节", enterprise: "绿源新能源科技", progress: 30, students: 4, stage: "原型开发", painPoint: "固定式光伏板效率低，需低成本追光方案", value: "学生做光敏传感器+步进电机方案" },
    { id: 5, name: "车间环境智能监测终端", enterprise: "瑞恒智能安防", progress: 55, students: 5, stage: "样机测试", painPoint: "需低成本温湿度+烟感一体化方案", value: "学生做传感器网络+数据回传，厂方给安装机会" },
  ],
  incubator: {
    active: 6, totalFunding: 85000, mentored: 28,
    stages: [{ name: "创意提交", count: 12, color: "#94a3b8" }, { name: "原型开发", count: 6, color: "#3b82f6" }, { name: "样机测试", count: 4, color: "#f59e0b" }, { name: "推向市场", count: 2, color: "#10b981" }],
    projects: [
      { id: 1, team: "智控未来", leader: "李明", members: 4, className: "电子2101", name: "校园智能浇灌系统", stage: "样机测试", progress: 80, desc: "土壤湿度传感器+电磁阀自动浇花，已在学校花圃实测", mentor: "刘主任", funding: 3000, avatar: "智" },
      { id: 2, team: "创想工作室", leader: "王磊", members: 5, className: "机电2101", name: "小型零件自动分拣机", stage: "原型开发", progress: 60, desc: "为本地五金厂开发低成本分拣装置，已获永利电子意向订单", mentor: "张老师", funding: 5000, avatar: "创" },
      { id: 3, team: "绿芯小队", leader: "陈静", members: 3, className: "电子2102", name: "家庭水位报警器", stage: "推向市场", progress: 92, desc: "低成本液位检测+短信告警，已做出50套在乡镇推广试用", mentor: "刘主任", funding: 2000, avatar: "绿" },
      { id: 4, team: "极光技术社", leader: "赵伟", members: 6, className: "计算机2101", name: "宿舍智能电表抄表系统", stage: "原型开发", progress: 45, desc: "ESP32+电流互感器实现宿舍用电远程抄表与超功率预警", mentor: "王老师", funding: 4000, avatar: "极" },
      { id: 5, team: "匠芯团队", leader: "周强", members: 4, className: "电子2101", name: "老人跌倒检测手环", stage: "创意提交", progress: 25, desc: "加速度传感器做跌倒检测+GSM一键呼救，面向农村留守老人", mentor: "张老师", funding: 0, avatar: "匠" },
      { id: 6, team: "启明星", leader: "吴敏", members: 3, className: "机电2101", name: "教室智能照明控制", stage: "创意提交", progress: 15, desc: "光照传感器+人体红外实现教室人来灯亮人走灯灭", mentor: "刘主任", funding: 0, avatar: "启" },
    ],
  },
  competitions: [
    { id: 1, name: "全省职业院校技能大赛", subTitle: "电子电路装调与应用", level: "省级", status: "备赛中", date: "2026年5月", students: 4, coach: "张老师", awards: "上届：二等奖" },
    { id: 2, name: "市级中职技能竞赛", subTitle: "单片机控制装置安装与调试", level: "市级", status: "集训中", date: "2026年4月", students: 6, coach: "刘主任", awards: "往届：团体一等奖" },
    { id: 3, name: "县级创新创业大赛", subTitle: "中职学生发明制作", level: "县级", status: "作品提交", date: "2026年3月", students: 8, coach: "王老师", awards: "去年：1金2银" },
  ],
  employmentStats: {
    rate2025: 94.5, rate2024: 92.8, rate2023: 90.1, avgSalary: 4200, salaryNote: "本地就业",
    topEnterprises: [
      { name: "永利电子厂", hires: 28, note: "电子组装/质检" }, { name: "华丰机械加工厂", hires: 22, note: "数控操作/维修" },
      { name: "县电力公司", hires: 15, note: "配电运维" }, { name: "县电信公司", hires: 12, note: "装维/机房值守" },
      { name: "省内电子企业", hires: 38, note: "SMT操作/调试" },
    ],
    destinations: [{ name: "本地就业", value: 55 }, { name: "省内其他城市", value: 30 }, { name: "升学深造", value: 10 }, { name: "自主创业", value: 5 }],
  },
  academic: {
    currentSemester: "2025-2026学年第二学期", totalClasses: 18, weeklySessions: 432,
    note: "仅管理STEM实训课程，不含文化课/学籍等通用教务",
    courses: [
      { name: "电子技术基础", grade: "2024级", students: 156, sessions: 6, teacher: "张老师", room: "电子理论教室 201", labHours: 2, type: "理论+实训" },
      { name: "单片机原理与应用", grade: "2023级", students: 128, sessions: 8, teacher: "刘主任", room: "嵌入式实验室 201", labHours: 4, type: "纯实训" },
      { name: "电工电子实训", grade: "2024级", students: 156, sessions: 4, teacher: "王老师", room: "电工电子实训中心", labHours: 4, type: "纯实训" },
      { name: "PLC控制技术", grade: "2023级", students: 85, sessions: 6, teacher: "李老师", room: "自动化实训室 301", labHours: 4, type: "纯实训" },
      { name: "传感器技术与应用", grade: "2023级", students: 128, sessions: 4, teacher: "张老师", room: "传感技术实验室 203", labHours: 3, type: "理论+实训" },
      { name: "电子CAD制图", grade: "2024级", students: 156, sessions: 4, teacher: "陈老师", room: "计算机机房 401", labHours: 2, type: "理论+实训" },
    ],
    labSchedule: [
      { lab: "嵌入式实验室 201", weeklySlots: 28, usedSlots: 22, utilization: 79, note: "单片机/嵌入式课程" },
      { lab: "电工电子实训中心", weeklySlots: 32, usedSlots: 26, utilization: 81, note: "电工电子/焊接实训" },
      { lab: "自动化实训室 301", weeklySlots: 24, usedSlots: 18, utilization: 75, note: "PLC/气动控制" },
      { lab: "传感技术实验室 203", weeklySlots: 20, usedSlots: 14, utilization: 70, note: "传感器/测量技术" },
      { lab: "创客工坊 101", weeklySlots: 16, usedSlots: 8, utilization: 50, note: "3D打印/孵化器项目" },
    ],
    teacherWorkload: [
      { name: "刘主任", courses: 4, weeklyHours: 18, classes: "电子2101/2102", load: "适中" },
      { name: "张老师", courses: 5, weeklyHours: 22, classes: "电子2201/机电2201", load: "偏重" },
      { name: "王老师", courses: 3, weeklyHours: 14, classes: "机电2101/2102", load: "适中" },
      { name: "李老师", courses: 3, weeklyHours: 16, classes: "机电2201", load: "适中" },
      { name: "陈老师", courses: 2, weeklyHours: 10, classes: "电子2201", load: "轻松" },
    ],
  },
  todaySchedule: [
    { time: "08:20", title: "单片机原理与应用", room: "嵌入式实验室 201", teacher: "刘主任", class: "电子2101", type: "嵌入式" },
    { time: "10:10", title: "电工电子实训", room: "电工电子实训中心", teacher: "王老师", class: "机电2201", type: "电工" },
    { time: "14:00", title: "PLC控制技术", room: "自动化实训室 301", teacher: "李老师", class: "机电2101", type: "PLC" },
    { time: "15:40", title: "双创孵化·项目辅导", room: "创客工坊 101", teacher: "张老师", class: "孵化器团队", type: "双创" },
  ],
  teacherTeam: [
    { name: "刘建国", role: "实训中心主任", skills: ["嵌入式开发", "PLC编程", "竞赛指导"], avatar: "刘", status: "在职", bio: "16年教龄", color: "from-purple-500 to-purple-700" },
    { name: "张志明", role: "电子技术讲师", skills: ["PCB设计", "传感器应用", "嵌入式"], avatar: "张", status: "上课中", bio: "12年教龄", color: "from-blue-500 to-blue-700" },
    { name: "王德华", role: "电工电子讲师", skills: ["电工基础", "焊接工艺", "电气维修"], avatar: "王", status: "在职", bio: "8年教龄", color: "from-green-500 to-green-700" },
    { name: "李永刚", role: "PLC/自动化讲师", skills: ["PLC编程", "气动控制", "组态"], avatar: "李", status: "在职", bio: "10年教龄", color: "from-orange-500 to-orange-700" },
    { name: "陈小燕", role: "计算机/CAD讲师", skills: ["CAD制图", "3D建模", "Python"], avatar: "陈", status: "在职", bio: "6年教龄", color: "from-teal-500 to-teal-700" },
    { name: "永利电子·刘工", role: "企业兼职讲师", skills: ["电子产品工艺", "质检规范", "产线管理"], avatar: "工", status: "每周1天驻校", bio: "永利电子技术主管", color: "from-slate-500 to-slate-700" },
  ],
  recentActivities: [
    { id: 1, type: "incubator", text: "绿芯小队「家庭水位报警器」首批50套试产，在3个乡镇推广中", time: "2小时前", icon: "🚀" },
    { id: 2, type: "cooperation", text: "永利电子厂将一条闲置流水线搬到学校，供学生实训和样机测试", time: "6小时前", icon: "🏭" },
    { id: 3, type: "achievement", text: "电子2101班李明团队获县创新创业大赛发明制作组一等奖", time: "1天前", icon: "🏆" },
    { id: 4, type: "equipment", text: "新到10套ESP32开发板，优先拨给孵化器团队使用", time: "2天前", icon: "📦" },
    { id: 5, type: "meeting", text: "与华丰机械加工厂商讨下阶段合作：学生参与机床数字化改造", time: "3天前", icon: "🤝" },
    { id: 6, type: "enrollment", text: "春季招生宣讲会：展示学生孵化产品水位报警器，反响热烈", time: "4天前", icon: "🎓" },
  ],
  budgetOverview: {
    annual: 1800000, spent: 1380000, remaining: 420000,
    items: [
      { name: "设备采购与维护", amount: 650000, percentage: 47 }, { name: "实训耗材", amount: 380000, percentage: 27 },
      { name: "校企合作及孵化器", amount: 180000, percentage: 13 }, { name: "竞赛与师资培训", amount: 120000, percentage: 9 }, { name: "其他", amount: 50000, percentage: 4 },
    ],
  },
};
